### ISSUE TITLE
Mixed Source

### ISSUE THREAD

**Issue by adilhayat17** [pelias/docker#132]
I have two questions
1) When does in search response in source field get "mixed" for certain addresses. I found them on following demo link
[https://pelias.github.io/compare/#/v1/search%3Ftext=1111%20MD%20760,%20Lusby,%20MD,%20USA](url) but not on my local deployment ?
2) I have OSM, OA, Tiger, WOF importers downloaded for MD and PA states of USA. But I am not able to get "1111 MD 760, Lusby, MD, USA" or even "MD 760, Lusby, MD, USA" on my local environment. But on demo link as mentioned above I get source as OSM for "MD 760, Lusby, MD, USA" address. 
today I downloaded again OSM and prepare all and import but no success with me. How can I get it. please can some one help me on it. Thanks.

My OSM source in config is `"sourceURL": "https://download.geofabrik.de/north-america/us/maryland-latest.osm.pbf" `

>

**Comment by adilhayat17** [comment]
@orangejulius  after posting that issue, I just noticed that there is a separate link for OpenStreetMap issues. So that why I posted it for OpenStrretMap over there.

**Comment by missinglink** [comment]
- Sources are 'mixed' when using the interpolation service, the interpolated data is generated from OSM/OA/TIGER data.
- Please `grep` the polylines file (`.0sv` file) for the text `'MD 760'` and let me know if it's present in that file?

**Comment by adilhayat17** [comment]
Thank you @missinglink for replying, I have two files with (`.0sv` file) extension under polylines directory.
1) Created from prepare `extract.0sv`
2) I downloaded from [https://geocode.earth/data](url) `planet-latestvalhalla.polylines.0sv`

Result of occurrence count using grep of 'MD 760' in `1` is 0 where as in `2` is 6.

**Comment by adilhayat17** [comment]
Hi @missinglink , I have read about polylines importer that it only supports one file at the top defined in config JSON. So, I tired using only one file in ploylines importer, the second one having planet data `planet-latestvalhalla.polylines.0sv` and it gave me `MD 760, Lusby, MD, USA` in results but still didn't gave me the complete address with house number. Now on prepare `extract.0sv` is made out of OpenStreetMap right. So, which one is recommended to use. One created by prepare step or one online I downloaded as one I downloaded provide me at least street address. Can you please suggest me or guide me for better results ?
One more thing I got follow error while doing `import all`
`error: [polyline] polyline document error message=invalid regex test, Open for public since April 2017. Source: https://finance.detik.com/berita-ekonomi-bisnis/3474957/jokowi-resmikan-tol-akses-tanjung-priok-siang-ini should not match /https?:\/\//, stack=PeliasModelError: invalid regex test, Open for public since April 2017. Source: https://finance.detik.com/berita-ekonomi-bisnis/3474957/jokowi-resmikan-tol-akses-tanjung-priok-siang-ini should not match /https?:\/\//
    at Object.nomatch (/code/pelias/polylines/node_modules/pelias-model/util/valid.js:117:13)
    at Document.setName (/code/pelias/polylines/node_modules/pelias-model/Document.js:259:18)
    at DestroyableTransform._transform (/code/pelias/polylines/stream/document.js:30:11)
    at DestroyableTransform.Transform._read (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Readable.read (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:440:10)
    at flow (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:920:34)
    at ParallelTransform.pipeOnDrainFunctionResult (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:730:7)
    at ParallelTransform.emit (events.js:182:13)
    at onwriteDrain (/code/pelias/polylines/node_modules/parallel-transform/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at afterWrite (/code/pelias/polylines/node_modules/parallel-transform/node_modules/readable-stream/lib/_stream_writable.js:489:18), name=PeliasModelError
error: [polyline] polyline document error message=invalid regex test, Open for Public Since April 2017. Source: https://finance.detik.com/berita-ekonomi-bisnis/3474957/jokowi-resmikan-tol-akses-tanjung-priok-siang-ini should not match /https?:\/\//, stack=PeliasModelError: invalid regex test, Open for Public Since April 2017. Source: https://finance.detik.com/berita-ekonomi-bisnis/3474957/jokowi-resmikan-tol-akses-tanjung-priok-siang-ini should not match /https?:\/\//
    at Object.nomatch (/code/pelias/polylines/node_modules/pelias-model/util/valid.js:117:13)
    at Document.setName (/code/pelias/polylines/node_modules/pelias-model/Document.js:259:18)
    at DestroyableTransform._transform (/code/pelias/polylines/stream/document.js:30:11)
    at DestroyableTransform.Transform._read (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at DestroyableTransform.Readable.read (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:440:10)
    at flow (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:920:34)
    at ParallelTransform.pipeOnDrainFunctionResult (/code/pelias/polylines/node_modules/readable-stream/lib/_stream_readable.js:730:7)
    at ParallelTransform.emit (events.js:182:13)
    at onwriteDrain (/code/pelias/polylines/node_modules/parallel-transform/node_modules/readable-stream/lib/_stream_writable.js:501:12)
    at afterWrite (/code/pelias/polylines/node_modules/parallel-transform/node_modules/readable-stream/lib/_stream_writable.js:489:18), name=PeliasModelError
`

**Comment by missinglink** [comment]
I would use the Valhalla file.

Both files are generated from OSM data but the Valhalla generation method is preferred.

The errors you posted above are nothing to worry about, they are caused when processing a record where someone has put a URL in a name field (which happens fails often in OSM unfortunately)

The error message is quite loud and scary, something we should probably change as you're not the first to report it!

**Comment by adilhayat17** [comment]
@missinglink , Thanks but still it is returning street only without housenumber. The Interpolation documentation says that is returns street when it does not have any address for that street. But I found 6 occurrences of `MD 760` in my `latestvalhalla`  file. Can you please guide me what else I can look into for achieving that?

**Comment by missinglink** [comment]
Please link to the section of the documentation you are referring to.
