### ISSUE TITLE
ERROR: Cannot start service

### ISSUE THREAD

**Issue by darmentrout** [pelias/docker#138]
While running the quick start script I get the following: 
```
+ pelias download all
ERROR: Cannot start service openstreetmap: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
ERROR: Cannot start service whosonfirst: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
ERROR: Cannot start service csv-importer: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
ERROR: Cannot start service transit: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
ERROR: Cannot start service interpolation: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
ERROR: Cannot start service openaddresses: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:365: sending config to init process caused \"write init-p: broken pipe\"": unknown
+ pelias prepare all
converting /data/openstreetmap/portland_oregon.osm.pbf to /data/polylines/extract.0sv
Creating extract at /data/placeholder/wof.extract
find: ‘/data/whosonfirst/data’: No such file or directory
Done!
```

This ultimately leads to 435 regression errors.
```
Aggregate test results
Pass: 0
Improvements: 0
Fail: 41
Placeholders: 0
Regressions: 435
Took 117904ms
Test success rate 8.61%

FATAL ERROR: 435 regression(s) detected.
```

I added pelias to my path. The output of `tr ':' '\n' <<< "$PATH"` is as follows:
```
/sbin
/bin
/usr/bin
/usr/local/bin
```

Ubuntu 18.04.3 LTS
Docker 19.03.4
docker-compose 1.17.1

**Comment by darmentrout** [comment]
I increased the amount of RAM available (12 GB) which resolved the "cannot start service" errors. Still getting 435 regression errors.

**Comment by darmentrout** [comment]
```
Investigate manually:
  curl http://api:4000/v1/search?text=pdx%20airport
Tests for: http://api:4000/v1 (docker)

/v1/search address
  ✘ regression [1] "/v1/search?text=4004 SW Beaverton-Hillsdale, Portland": no results returned

/v1/search address
  ✘ regression [1] "/v1/search?text=777 NE MLK Blvd, Portland, OR": no results returned
  ✘ regression [2] "/v1/search?text=777 NE MLK Blvd, Portland, Oregon": no results returned
  ✘ regression [3] "/v1/search?text=777 NE MLK Blvd Portland OR": no results returned
  ✘ regression [4] "/v1/search?text=777 NE MLK Blvd Portland Oregon": no results returned
  ✘ regression [5] "/v1/search?text=777 NE MLK Jr Blvd, Portland, OR": no results returned
  ✘ regression [6] "/v1/search?text=777 NE MLK Jr Blvd, Portland, Oregon": no results returned
  ✘ regression [7] "/v1/search?text=777 NE MLK Jr Blvd Portland OR": no results returned
  ✘ regression [8] "/v1/search?text=777 NE MLK Jr Blvd Portland Oregon": no results returned
  ✘ regression [9] "/v1/search?text=777 NE ML King Blvd, Portland, OR": no results returned
  ✘ regression [10] "/v1/search?text=777 NE ML King Blvd, Portland, Oregon": no results returned
  ✘ regression [11] "/v1/search?text=777 NE ML King Blvd Portland OR": no results returned
  ✘ regression [12] "/v1/search?text=777 NE ML King Blvd Portland Oregon": no results returned
  ✘ regression [12.1] "/v1/search?text=777 NE martin luther king Portland Oregon": no results returned

```

**Comment by missinglink** [comment]
Increasing your RAM and the response error you pasted `Timeout of 250ms exceeded` both point to environmental issues.
I'm sorry I can't be more helpful but I suspect the issue is with how you have your machine configured and not with the code.

**Comment by missinglink** [comment]
FYI I can easily run a project like `portland-metro` on my laptop (16GB RAM).
Did you reimport the data after you increased the RAM?

**Comment by darmentrout** [comment]
I have 8 CPUs and 12 GB RAM. I deleted /code and /data and started from scratch. 
```
Tests for: http://api:4000/v1 (docker)

/v1/search address
  ✘ regression [1] "/v1/search?text=4004 SW Beaverton-Hillsdale, Portland": no results returned
```
…
```
Aggregate test results
Pass: 0
Improvements: 0
Fail: 41
Placeholders: 0
Regressions: 435
Took 38689ms
Test success rate 8.61%

FATAL ERROR: 435 regression(s) detected.
```

**Comment by darmentrout** [comment]
I logged out and quit XFCE. I SSHed into the machine and did a clean reinstall. At its height, the installer used a little over 75% of the CPU and 63% of the RAM.  The only error along the way I received is below (but no regression errors during the test phase). 

```
+ pelias download all
error downloading: whosonfirst-data-latest.db

/code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:45
        return new CPPDatabase(filename, filenameGiven, memory || anonymous, readonly, fileMustExist, timeout, verbose || null);
               ^
SqliteError: unable to open database file
    at new Database (/code/pelias/whosonfirst/node_modules/better-sqlite3/lib/database.js:45:9)
    at findSubdivisions (/code/pelias/whosonfirst/utils/sqlite_extract_data.js:195:12)
    at /code/pelias/whosonfirst/utils/download_data.js:19:26
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:2959:19
    at wrapper (/code/pelias/whosonfirst/node_modules/async/dist/async.js:272:20)
    at iterateeCallback (/code/pelias/whosonfirst/node_modules/async/dist/async.js:425:28)
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:325:20
    at /code/pelias/whosonfirst/node_modules/async/dist/async.js:2957:17
    at ChildProcess.<anonymous> (/code/pelias/whosonfirst/utils/sqlite_download.js:45:9)
    at ChildProcess.emit (events.js:209:13)
```

**Comment by darmentrout** [comment]
Closing: The service started after installation and I am no longer getting regression errors. 
I still need to troubleshoot the following error: `error downloading: whosonfirst-data-latest.db`
