### ISSUE TITLE
"pelias elastic create" result in "connect EHOSTUNREACH 172.18.0.2:9200 - No Living Connections"

### ISSUE THREAD

**Issue by Fr3dY2** [pelias/docker#167]
Hi,

I'm trying to install pelias on **RHEL 8.1** and it fails in the "**pelias elastic create**" command.
I defined the proxy variables in Docker service scripts to make "**pelias compose pull**" work, but can't get past the index creation in ElasticSearch.
However, both "**pelias elastic wait**" and "**telnet 172.18.0.2 9200**" work fine.
I'm using **containerd.io-1.2.6-3.3**, **docker-ce-19.03.5-3.el7** and **docker-compose-1.25.0**.

Basically, this is what I did:

**vi /usr/lib/systemd/system/docker.service** <-- Under [Service], add:
Environment="HTTP_PROXY=http://proxyuser:proxypassword@proxyip:proxyport/"
Environment="HTTPS_PROXY=http://proxyuser:proxypassword@proxyip:proxyport/"

**pelias compose pull**
Pulling libpostal ... done
Pulling schema ... done
Pulling api ... done
Pulling placeholder ... done
Pulling whosonfirst ... done
Pulling openstreetmap ... done
Pulling openaddresses ... done
Pulling transit ... done
Pulling csv-importer ... done
Pulling polylines ... done
Pulling interpolation ... done
Pulling pip ... done
Pulling elasticsearch ... done
Pulling fuzzy-tester ... done

**pelias elastic start**
Creating network "pelias_default" with driver "bridge"
Creating pelias_elasticsearch ... done

**pelias elastic wait**
waiting for elasticsearch service to come up
......Elasticsearch up!

**pelias elastic create**

create index

Elasticsearch ERROR: 2020-01-16T16:02:28Z
  Error: Request error, retrying
  GET http://elasticsearch:9200/ => connect EHOSTUNREACH 172.18.0.2:9200
	  at Log.error (/code/pelias/schema/node_modules/elasticsearch/src/lib/log.js:239:56)
	  at checkRespForFailure (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:298:18)
	  at HttpConnector.<anonymous> (/code/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
	  at ClientRequest.wrapper (/code/pelias/schema/node_modules/lodash/lodash.js:4929:19)
	  at ClientRequest.emit (events.js:209:13)
	  at Socket.socketErrorListener (_http_client.js:406:9)
	  at Socket.emit (events.js:209:13)
	  at emitErrorNT (internal/streams/destroy.js:91:8)
	  at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
	  at processTicksAndRejections (internal/process/task_queues.js:77:11)

Elasticsearch WARNING: 2020-01-16T16:02:29Z
  Unable to revive connection: http://elasticsearch:9200/

Elasticsearch WARNING: 2020-01-16T16:02:29Z
  No living connections

NoConnections [Error]: No Living connections
	at sendReqWithConnection (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:266:15)
	at next (/code/pelias/schema/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)
	at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  message: 'No Living connections'
}
unsupported elasticsearch version. try: >=6.5.4 || >=7.4.2

**Comment by Fr3dY2** [comment]
OK, fixed by putting this in /etc/sysctl.conf:
**net.bridge.bridge-nf-call-iptables = 0**

Looks like in RHEL 8.1 something changed and traffic in bridged interface goes thru proxy/iptables.
Disabling it makes it work:

**[put mapping]    pelias { acknowledged: true, shards_acknowledged: true, index: 'pelias' }**

Now I'm stuck at "**pelias download all**" step... wget and curl commands are trying to connect directly, instead using proxy. I've tried putting **network_mode: host** in docker-compose.yml but still not working :(

**Comment by Fr3dY2** [comment]
OK, fixed by using **proxychains-ng** and forcing http/https requests to go through proxy in a transparent way (valid for any other projects using Docker)
