### ISSUE TITLE
Download all error

### ISSUE THREAD

**Issue by Freshm4at** [pelias/docker#261]
Hi Guys, 
I try to setup pelias on AWS. I already install pelias docker on local server without any issues but now i try to reproduce the installation on an xlarge AWS server (8Go RAM)

**Describe the bug**

**Steps to Reproduce**

i follow the README installation instruction 
and run the command "pelias download all"

**Environment (please complete the following information):**

Linux AWS server with docker and docker-compose latest version

**Pastebin/Screenshots**

![Capture du 2021-05-18 13-01-28](https://user-images.githubusercontent.com/74661160/118641607-a7267100-b7da-11eb-89af-085eeafd4b7d.png)

**Additional context**

I modify nothing in the original france project

### logs 
When i check log with pelias compose logs, i have this : 

interpolation_1  | TypeError: Cannot open database because the directory does not exist
interpolation_1  |     at new Database (/code/pelias/interpolation/node_modules/better-sqlite3/lib/database.js:33:9)
interpolation_1  |     at setup (/code/pelias/interpolation/api/search.js:12:14)
interpolation_1  |     at Object.<anonymous> (/code/pelias/interpolation/cmd/server.js:32:11)
interpolation_1  |     at Module._compile (internal/modules/cjs/loader.js:955:30)
interpolation_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
interpolation_1  |     at Module.load (internal/modules/cjs/loader.js:811:32)
interpolation_1  |     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
interpolation_1  |     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
interpolation_1  |     at internal/main/run_main_module.js:17:11
interpolation_1  | /code/pelias/interpolation/node_modules/better-sqlite3/lib/database.js:33
interpolation_1  | 		throw new TypeError('Cannot open database because the directory does not exist');
interpolation_1  | 		^

placeholder_1    | TypeError: Cannot open database because the directory does not exist
placeholder_1    |     at new Database (/code/pelias/placeholder/node_modules/better-sqlite3/lib/database.js:32:9)
placeholder_1    |     at DocStore.Database.open (/code/pelias/placeholder/lib/Database.js:17:13)
placeholder_1    |     at Placeholder.module.exports.load (/code/pelias/placeholder/prototype/io.js:10:14)
placeholder_1    |     at Object.<anonymous> (/code/pelias/placeholder/server/http.js:68:4)
placeholder_1    |     at Module._compile (internal/modules/cjs/loader.js:955:30)
placeholder_1    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
placeholder_1    |     at Module.load (internal/modules/cjs/loader.js:811:32)
placeholder_1    |     at Function.Module._load (internal/modules/cjs/loader.js:723:14)
placeholder_1    |     at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
placeholder_1    |     at internal/main/run_main_module.js:17:11
placeholder_1    | /code/pelias/placeholder/node_modules/better-sqlite3/lib/database.js:32
placeholder_1    | 		throw new TypeError('Cannot open database because the directory does not exist');
placeholder_1    | 		^

Thanks :)

**Comment by missinglink** [comment]
Hi @Freshm4at, I'm trying to understand this screenshot, it looks like you hit `Control+C` a couple times to cancel the `pelias download all` command?

**Comment by stouch** [comment]
I had the same error but you just have to follow the docs : Don't just run docker compose up -> You must execute the setup shell script (including pelias compose up etc..)
