### ISSUE TITLE
PeliasModelError: invalid regex test, https://yavuzgallery.com should not match /https?:\/\//

### ISSUE THREAD

**Issue by vctqs1** [pelias/docker#329]
**Describe the bug**
```
error: [openstreetmap] tag_mapper error
error: [openstreetmap] PeliasModelError: invalid regex test, https://mustsharenews.com/changi-airport-taxiway-bridge should not match /https?:\/\//
    at Object.nomatch (/code/pelias/openstreetmap/node_modules/pelias-model/util/valid.js:117:13)
    at Document.setNameAlias (/code/pelias/openstreetmap/node_modules/pelias-model/Document.js:263:18)
    at /code/pelias/openstreetmap/stream/tag_mapper.js:53:19
    at /code/pelias/openstreetmap/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/code/pelias/openstreetmap/node_modules/lodash/lodash.js:3032:24)
    at /code/pelias/openstreetmap/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/code/pelias/openstreetmap/node_modules/lodash/lodash.js:9410:14)
    at DestroyableTransform._transform (/code/pelias/openstreetmap/stream/tag_mapper.js:34:9)
    at DestroyableTransform.Transform._read (/code/pelias/openstreetmap/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at DestroyableTransform.Readable.read (/code/pelias/openstreetmap/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:428:10)
error: [openstreetmap] {
  "name": {},
  "parent": {},
  "address_parts": {},
  "center_point": {
    "lon": 103.981672,
    "lat": 1.341471
  },
  "category": [],
  "addendum": {},
  "source": "openstreetmap",
  "layer": "venue",
  "source_id": "way/1160231091",
  "bounding_box": "{\"min_lat\":1.34075,\"max_lat\":1.3419159,\"min_lon\":103.9807734,\"max_lon\":103.9835476}"
}
```

**Steps to Reproduce**
1. installing https://github.com/pelias/docker/tree/master/projects/singapore
2. Run 'pelias import all'
3. See error

**Expected behavior**
Remove this error

**Environment (please complete the following information):**
 - OS: Mac
 - Docker versions:  Docker version 24.0.6, build ed223bc, Docker Compose version v2.23.0-desktop.1 

**Pastebin/Screenshots**
![image](https://github.com/pelias/docker/assets/30227910/29eecd91-124d-4faf-a8eb-56b841bb9361)

**Comment by missinglink** [comment]
These are just warnings, you can ignore them.
It's triggered by a data error where there is a URL in one of the name fields of `way/1160231091`

**Comment by missinglink** [comment]
I've fixed the offending record in OSM https://www.openstreetmap.org/way/1160231091

<img width="909" alt="Screenshot 2023-11-21 at 15 01 06" src="https://github.com/pelias/docker/assets/738069/3393cbbf-e065-4d56-8639-36ed02649530">
