### ISSUE TITLE
error - no living connections, pls install mandatory plugins before continuing

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#52]
I am getting the mystery error below - any help appreciated, for instance what might be the 'mandatory plugins' and why wouldnt those already be in the container, whatever they are...

```
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias elastic create
Elasticsearch ERROR: 2018-11-26T12:29:02Z
  Error: Request error, retrying
  GET http://elasticsearch:9200/_nodes => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200
      at Log.error (/code/pelias/schema/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/code/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.js:163:7)
      at ClientRequest.wrapper (/code/pelias/schema/node_modules/lodash/lodash.js:4935:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:391:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

Elasticsearch WARNING: 2018-11-26T12:29:03Z
  Unable to revive connection: http://elasticsearch:9200/

Elasticsearch WARNING: 2018-11-26T12:29:03Z
  No living connections

{ Error: No Living connections
    at sendReqWithConnection (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:226:15)
    at next (/code/pelias/schema/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
    at process._tickCallback (internal/process/next_tick.js:61:11) message: 'No Living connections' }
please install mandatory plugins before continuing.

```

**Comment by jeremy-rutman** [comment]
pelias test run also returns the enotfound error 

```
root@jeremy-TECRA-Z40-C-pipl:/home/jeremy/pelias_docker/docker/projects/portland-metro# pelias test run 
{ Error: getaddrinfo ENOTFOUND api api:4000
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api',
  host: 'api',
  port: '4000' }


```

**Comment by jeremy-rutman** [comment]
sorry once again that was a lingering effect of the snap install . deracinating snap and killing remaining processes took care of it

**Comment by orangejulius** [comment]
It's really interesting that using `snap` caused so many issues. We've found it to be problematic as well. Thanks for letting us know

**Comment by jeremy-rutman** [comment]
I am hitting this again on a new machine and new installs of everything - this time snap not involved. `systemctl restart docker` didn't help

**Comment by jeremy-rutman** [comment]
BTW - if I have one project running, will this prevent others from running? E.g. I have a machine  running `pelias prepare all` (for project portland-metro)  , can i now run `pelias elastic create` in a different project (eg planet) ?
