### ISSUE TITLE
pelias import all error ENOTFOUND

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#80]
after `pelias prepare all` worked, I now get another ENOTFOUND error as below...
```
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias prepare all
...
Build completed!

deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias import all
info: [whosonfirst] Loading whosonfirst-data-continent-latest.csv records from /data/whosonfirst/meta
Elasticsearch ERROR: 2019-03-18T22:07:11Z
  Error: Request error, retrying
  HEAD http://elasticsearch:9200/pelias => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200
      at Log.error (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
      at ClientRequest.wrapper (/code/pelias/whosonfirst/node_modules/lodash/lodash.js:4935:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

info: [whosonfirst] Loading whosonfirst-data-country-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-region-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-county-latest.csv records from /data/whosonfirst/meta
Elasticsearch WARNING: 2019-03-18T22:07:11Z
  Unable to revive connection: http://elasticsearch:9200/

Elasticsearch WARNING: 2019-03-18T22:07:11Z
  No living connections

ERROR: Elasticsearch index pelias does not exist
You must use the pelias-schema tool (https://github.com/pelias/schema/) to create the index first
For full instructions on setting up Pelias, see http://pelias.io/install.html
/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38
          throw new Error(`elasticsearch index ${config.schema.indexName} does not exist`);
          ^

Error: elasticsearch index pelias does not exist
    at existsCallback (/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38:17)
    at respond (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:327:9)
    at sendReqWithConnection (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:226:7)
    at next (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias elastic status
200

```

**Comment by missinglink** [comment]
The output of `pelias compose ps` should show an elasticsearch container running on port 9200

**Comment by missinglink** [comment]
The message `Elasticsearch index pelias does not exist` indicates that you have skipped steps in the README.

**Comment by jeremy-rutman** [comment]
i'll try again from scratch using pelias elastic stop , tho i blv i went thru all the steps as per the readme

**Comment by jeremy-rutman** [comment]
stop/start/wait/create/download all/prepare all/import all hit more or less the same error as above, 

```
info: [whosonfirst] Loading whosonfirst-data-continent-latest.csv records from /data/whosonfirst/meta
Elasticsearch ERROR: 2019-03-19T11:31:46Z
  Error: Request error, retrying
  HEAD http://elasticsearch:9200/pelias => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200
      at Log.error (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
      at ClientRequest.wrapper (/code/pelias/whosonfirst/node_modules/lodash/lodash.js:4935:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

info: [whosonfirst] Loading whosonfirst-data-country-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-region-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-county-latest.csv records from /data/whosonfirst/meta
Elasticsearch WARNING: 2019-03-19T11:31:46Z
  Unable to revive connection: http://elasticsearch:9200/

Elasticsearch WARNING: 2019-03-19T11:31:46Z
  No living connections

ERROR: Elasticsearch index pelias does not exist
You must use the pelias-schema tool (https://github.com/pelias/schema/) to create the index first
For full instructions on setting up Pelias, see http://pelias.io/install.html
/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38
          throw new Error(`elasticsearch index ${config.schema.indexName} does not exist`);
          ^

Error: elasticsearch index pelias does not exist
    at existsCallback (/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38:17)
    at respond (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:327:9)
    at sendReqWithConnection (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:226:7)
    at next (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)

```

On the assumption that the index_already_exists_exception was a showstopper I will try to restart everything from scratch by a docker restart , as `pelias elastic stop` doesn't seem to do the trick

**Comment by jeremy-rutman** [comment]
`sudo systemctl daemon-reload`  `sudo systemctl restart docker` `pelias compose pull` `pelias elastic start` `pelias elastic wait` `pelias elastic create` hit the same index_already_exists_exception `([index_already_exists_exception] index [pelias/k0Hmz31MTbG9SJYCo0JINg] already exists, with { index_uuid="k0Hmz31MTbG9SJYCo0JINg" & index="pelias" } `  so I'll try again with a different data_dir in .env on the assumption that the index being found is saved there

**Comment by jeremy-rutman** [comment]
so after moving the data_dir and starting over, I once again hit the same err .
changed data_dir in .env to a new dir , then 

```pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download all
pelias prepare all
```
and then 

```deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias import all
info: [whosonfirst] Loading whosonfirst-data-continent-latest.csv records from /data/whosonfirst/meta
Elasticsearch ERROR: 2019-03-19T13:34:23Z
  Error: Request error, retrying
  HEAD http://elasticsearch:9200/pelias => getaddrinfo ENOTFOUND elasticsearch elasticsearch:9200
      at Log.error (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/log.js:226:56)
      at checkRespForFailure (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:259:18)
      at HttpConnector.<anonymous> (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
      at ClientRequest.wrapper (/code/pelias/whosonfirst/node_modules/lodash/lodash.js:4935:19)
      at ClientRequest.emit (events.js:182:13)
      at Socket.socketErrorListener (_http_client.js:392:9)
      at Socket.emit (events.js:182:13)
      at emitErrorNT (internal/streams/destroy.js:82:8)
      at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
      at process._tickCallback (internal/process/next_tick.js:63:19)

info: [whosonfirst] Loading whosonfirst-data-country-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-region-latest.csv records from /data/whosonfirst/meta
info: [whosonfirst] Loading whosonfirst-data-county-latest.csv records from /data/whosonfirst/meta
Elasticsearch WARNING: 2019-03-19T13:34:23Z
  Unable to revive connection: http://elasticsearch:9200/

Elasticsearch WARNING: 2019-03-19T13:34:23Z
  No living connections

ERROR: Elasticsearch index pelias does not exist
You must use the pelias-schema tool (https://github.com/pelias/schema/) to create the index first
For full instructions on setting up Pelias, see http://pelias.io/install.html
/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38
          throw new Error(`elasticsearch index ${config.schema.indexName} does not exist`);
          ^

Error: elasticsearch index pelias does not exist
    at existsCallback (/code/pelias/whosonfirst/node_modules/pelias-dbclient/src/configValidation.js:38:17)
    at respond (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:327:9)
    at sendReqWithConnection (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/transport.js:226:7)
    at next (/code/pelias/whosonfirst/node_modules/elasticsearch/src/lib/connection_pool.js:214:7)
    at process._tickCallback (internal/process/next_tick.js:61:11)
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ curl -H http://localhost:9200
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ curl -H 'http://localhost:9200'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias elastic status
200
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/portland-metro$ pelias compose ps
        Name                   Command           State                       Ports                     
-------------------------------------------------------------------------------------------------------
pelias_elasticsearch   /bin/bash bin/es-docker   Up      0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp```

**Comment by jeremy-rutman** [comment]
All our servers use a corporate proxy and I don;t blv I'll get an ok around that.  I set   network_mode: host for  a few services in the docker-compose.yml, which worked for allowing downloads  but it seems is causing trouble here  ; I'll see if adding such a line e..g to api and/or schema will  take care of it . Adding this line to 'elasticsearch' does cause trouble in the `pelias elastic create` step.
In any case if I manage to get to the other side of this maybe its of use to other corporate users

**Comment by jeremy-rutman** [comment]
a working kluge  seems to be: add network_mode:host for services osm, oaddr and anything else requiring net access  during `pelias download all`, then take out the network_mode lines , stop/start the elastic and continue  to `prepare all` .

**Comment by jeremy-rutman** [comment]
in some proxy setups you might need to pass in the proxy values as environment variables, which conveniently enough can be done in the docker.yaml , for instance:

  whosonfirst:
    environment:
      - http_proxy=http://my.proxy.com:3128
      - https_proxy=http://my.proxy.com:3128      
      - HTTP_PROXY=http://my.proxy.com:3128
      - HTTPS_PROXY=http://my.proxy.com:3128      
    network_mode: host

**Comment by Fr3dY2** [comment]
Hi,

I'm trying to install pelias on RHEL 8.1 and it fails in the 'pelias elastic create' command as well.
I defined the proxy variables in Docker service scripts to make "pelias compose pull" work, but can't get past the index creation in ElasticSearch.
However, both "**pelias elastic wait**" and "**telnet 172.18.0.2 9200**" work fine.
I'm using **containerd.io-1.2.6-3.3**, **docker-ce-19.03.5-3.el7** and **docker-compose-1.25.0**.

Basically, this is what I did:

**vi /usr/lib/systemd/system/docker.service** <-- Under [Service], add:
Environment="HTTP_PROXY=http://proxyuser:proxypassword@proxyip:proxyport/"
Environment="HTTPS_PROXY=http://proxyuser:proxypassword@proxyip:proxyport/"

**pelias compose pull**
	Pulling libpostal     ... done
	Pulling schema        ... done
	Pulling api           ... done
	Pulling placeholder   ... done
	Pulling whosonfirst   ... done
	Pulling openstreetmap ... done
	Pulling openaddresses ... done
	Pulling transit       ... done
	Pulling csv-importer  ... done
	Pulling polylines     ... done
	Pulling interpolation ... done
	Pulling pip           ... done
	Pulling elasticsearch ... done
	Pulling fuzzy-tester  ... done

**pelias elastic start**
	Creating network "pelias_default" with driver "bridge"
	Creating pelias_elasticsearch ... done

**pelias elastic wait**
	waiting for elasticsearch service to come up
	......Elasticsearch up!

**pelias elastic create**
	--------------
	 create index
	--------------

	Elasticsearch ERROR: 2020-01-16T16:02:28Z
	  Error: Request error, retrying
	  GET http://elasticsearch:9200/ => connect EHOSTUNREACH 172.18.0.2:9200
		  at Log.error (/code/pelias/schema/node_modules/elasticsearch/src/lib/log.js:239:56)
		  at checkRespForFailure (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:298:18)
		  at HttpConnector.<anonymous> (/code/pelias/schema/node_modules/elasticsearch/src/lib/connectors/http.js:171:7)
		  at ClientRequest.wrapper (/code/pelias/schema/node_modules/lodash/lodash.js:4929:19)
		  at ClientRequest.emit (events.js:209:13)
		  at Socket.socketErrorListener (_http_client.js:406:9)
		  at Socket.emit (events.js:209:13)
		  at emitErrorNT (internal/streams/destroy.js:91:8)
		  at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
		  at processTicksAndRejections (internal/process/task_queues.js:77:11)

	Elasticsearch WARNING: 2020-01-16T16:02:29Z
	  Unable to revive connection: http://elasticsearch:9200/

	Elasticsearch WARNING: 2020-01-16T16:02:29Z
	  No living connections

	NoConnections [Error]: No Living connections
		at sendReqWithConnection (/code/pelias/schema/node_modules/elasticsearch/src/lib/transport.js:266:15)
		at next (/code/pelias/schema/node_modules/elasticsearch/src/lib/connection_pool.js:243:7)
		at processTicksAndRejections (internal/process/task_queues.js:75:11) {
	  message: 'No Living connections'
	}
	unsupported elasticsearch version. try: >=6.5.4 || >=7.4.2

**Comment by Adriano-Silva-DEV** [comment]
Estou com este mesmo erro, conseguiu resolver?
