### ISSUE TITLE
pelias download wof   doesnt seem to run on it own

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#92]
`pelias download wof` hits a fail on curl  when imports.whosonfirst.sqlite is true
```
deploy@dap-jupyter01:/mnt/open_street_map/pelias_docker/docker/projects/planet$ pelias download wof
child_process.js:637
    throw err;
    ^

Error: Command failed: curl --silent -L https://dist.whosonfirst.org/sqlite/inventory.json
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at module.exports (/code/pelias/whosonfirst/node_modules/download-file-sync/index.js:3:6)
    at generateSQLites (/code/pelias/whosonfirst/utils/download_sqlite_all.js:26:32)
    at Object.download (/code/pelias/whosonfirst/utils/download_sqlite_all.js:63:29)
    at Object.<anonymous> (/code/pelias/whosonfirst/utils/download_data.js:66:38)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```
the command ` curl --silent -L https://dist.whosonfirst.org/sqlite/inventory.json` will run at the cli

**Comment by jeremy-rutman** [comment]
closing and moving to wof subrepo
