### ISSUE TITLE
pelias import all - log4j error 

### ISSUE THREAD

**Issue by jeremy-rutman** [pelias/docker#98]
After 
```
pelias elastic start
pelias elastic wait
```
I am getting a conitnually-restarting pelias_elasticsearch process as seen by `pelias compose ps`. The logs (`pelias compose logs`) show repeated cases of the following:

```
elasticsearch_1  | log4j:WARN No appenders could be found for logger (bootstrap).
elasticsearch_1  | log4j:WARN Please initialize the log4j system properly.
elasticsearch_1  | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
elasticsearch_1  | Exception in thread "main" java.lang.IllegalStateException: Unable to access 'path.scripts' (/usr/share/elasticsearch/config/scripts)
elasticsearch_1  | Likely root cause: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/scripts
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:674)
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:767)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:337)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Security.addPath(Security.java:314)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:248)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:212)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Security.configure(Security.java:118)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setupSecurity(Bootstrap.java:212)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:183)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:45)
elasticsearch_1  | Refer to the log for complete error details.
```
The only slightly nonstandard thing in my pelias.json file was a portmap 
`    elasticsearch.ports= [ "9700:9200", "9800:9300" ]` , which was accompanied by setting ELASTIC_HOST=localhost:9700 in .env such that the command [elastic_status](https://github.com/pelias/docker/blob/master/cmd/elastic.sh) refers to the correct port.  Trying again after changing to the default values  (`pelias compose down`,`pelias elastic start`,`pelias elastic wait`) didn't help matters. 
Given the 'access denied' I tried also using sudo but this didnt help either - I imagine the user being denied is the pelias user running the commands in a container .

**Comment by jeremy-rutman** [comment]
This seems to have gone away after removal of another nonstandard line I forgot about , namely  a directory map of /usr/share/elasticsearch/config  to a subdir of DATA_DIR .  Not entirely sure that's the reason .
